<?php
namespace Melete\ORM\Illuminate;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-22 at 06:17:27.
 */
class MeleteCapsuleTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MeleteCapsule
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $connection = array (
            'driver'    => 'mysql',
            'host'      => 'localhost',
            'database'  => 'database',
            'username'  => 'root',
            'password'  => 'password',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        );
        $this->object = new MeleteCapsule($connection);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    
}
