<?php

use Melete\Tests\TestCase as TestCase;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-23 at 07:01:29.
 */
class UserTest extends TestCase
{

    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $this->object = new User();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
