<?php
namespace Melete\Business\Helpers;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-22 at 04:30:04.
 */
class AbstractConfigLoaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AbstractConfigLoader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AbstractConfigLoader;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
