<?php
namespace Melete\Business;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-22 at 04:28:03.
 */
class ConfigurationProviderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ConfigurationProvider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConfigurationProvider;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Melete\Business\ConfigurationProvider::getConfigValue
     * @todo   Implement testGetConfigValue().
     */
    public function testGetConfigValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
