<?php
namespace Melete\Business;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-22 at 04:30:35.
 */
class UserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new User;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Melete\Business\User::getDailyLimitOverride
     * @todo   Implement testGetDailyLimitOverride().
     */
    public function testGetDailyLimitOverride()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Melete\Business\User::getWeeklyLimitOverride
     * @todo   Implement testGetWeeklyLimitOverride().
     */
    public function testGetWeeklyLimitOverride()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Melete\Business\User::getMonthlyLimitOverride
     * @todo   Implement testGetMonthlyLimitOverride().
     */
    public function testGetMonthlyLimitOverride()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Melete\Business\User::getDailyLimit
     * @todo   Implement testGetDailyLimit().
     */
    public function testGetDailyLimit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Melete\Business\User::getWeeklyLimit
     * @todo   Implement testGetWeeklyLimit().
     */
    public function testGetWeeklyLimit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Melete\Business\User::getMonthlyLimit
     * @todo   Implement testGetMonthlyLimit().
     */
    public function testGetMonthlyLimit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Melete\Business\User::getSentToday
     * @todo   Implement testGetSentToday().
     */
    public function testGetSentToday()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Melete\Business\User::getSentThisWeek
     * @todo   Implement testGetSentThisWeek().
     */
    public function testGetSentThisWeek()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Melete\Business\User::getSentThisMonth
     * @todo   Implement testGetSentThisMonth().
     */
    public function testGetSentThisMonth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
