<?php


use Melete\Business\UserList;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-22 at 04:30:35.
 */
class UserListTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var UserList
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UserList;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers UserList::clearUsers
     * @todo   Implement testClearUsers().
     */
    public function testClearUsers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
