<?php
namespace Melete\Rules;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-22 at 04:31:18.
 */
class AbstractRulesTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AbstractRules
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AbstractRules;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Melete\Rules\AbstractRules::loadConfig
     * @todo   Implement testLoadConfig().
     */
    public function testLoadConfig()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Melete\Rules\AbstractRules::getConfig
     * @todo   Implement testGetConfig().
     */
    public function testGetConfig()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
